# Generated by Django 5.1.3 on 2025-01-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="pic")),
                ("name", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image1", models.ImageField(default="parti.jpg", upload_to="pic")),
                ("image2", models.ImageField(default="parti.jpg", upload_to="pic")),
                ("image3", models.ImageField(default="parti.jpg", upload_to="pic")),
                ("image4", models.ImageField(default="parti.jpg", upload_to="pic")),
                ("image5", models.ImageField(default="parti.jpg", upload_to="pic")),
                ("image6", models.ImageField(default="parti.jpg", upload_to="pic")),
            ],
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="dj.jpg", upload_to="pic")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Parties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="parti.jpg", upload_to="pic")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Planner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="car.jpg", upload_to="pic")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Resort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="resort1.jpg", upload_to="pic")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Stories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="dj.jpg", upload_to="pic")),
                ("name", models.CharField(max_length=50)),
                ("desc", models.CharField(default="nothing", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="UserRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("password", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("tailor", "Tailor"),
                            ("catering", "Catering"),
                            ("entertainer", "Entertainer"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=200)),
                ("booking_date", models.DateField()),
                ("booked_on", models.DateField(auto_now=True)),
                (
                    "advance_payment",
                    models.DecimalField(
                        decimal_places=2, default=5000.0, max_digits=10
                    ),
                ),
                (
                    "total_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.events"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tailor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="tailor1.jpg", upload_to="pic")),
                ("name", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=500)),
                ("available", models.BooleanField(default=True)),
                (
                    "username",
                    models.ForeignKey(
                        limit_choices_to={"category": "tailor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.userregister",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.userregister",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entertainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="tailor1.jpg", upload_to="pic")),
                ("name", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=500)),
                ("available", models.BooleanField(default=True)),
                (
                    "username",
                    models.ForeignKey(
                        limit_choices_to={"category": "entertainer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.userregister",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Catering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="tailor1.jpg", upload_to="pic")),
                ("name", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=500)),
                ("available", models.BooleanField(default=True)),
                (
                    "username",
                    models.ForeignKey(
                        limit_choices_to={"category": "catering"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.userregister",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("booking_date", models.DateField()),
                ("booked_on", models.DateField(auto_now=True)),
                (
                    "advance_payment",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "tailor_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "caterer_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "entertainer_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.booking"
                    ),
                ),
                (
                    "catering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.catering",
                    ),
                ),
                (
                    "entertainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.entertainer",
                    ),
                ),
                (
                    "tailor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.tailor",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        limit_choices_to={"category": "user"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.userregister",
                    ),
                ),
            ],
        ),
    ]
