# Generated by Django 5.1.3 on 2025-01-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_booking_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-booked_on"],
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
            },
        ),
        migrations.RemoveField(
            model_name="booking",
            name="username",
        ),
    ]
