# Generated by Django 5.1.3 on 2025-01-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_remove_booking_user_booking_user_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="username",
            field=models.CharField(default=2, max_length=50),
        ),
    ]
