# Generated by Django 5.1.3 on 2025-01-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_booking_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="user_details",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.userregister"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
