# Generated by Django 5.1.3 on 2025-01-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_alter_booking_user_details_alter_booking_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminbooking",
            name="advance_payment",
        ),
    ]
