# Generated by Django 5.1.3 on 2025-01-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_remove_adminbooking_advance_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminbooking",
            name="address",
        ),
        migrations.RemoveField(
            model_name="adminbooking",
            name="booking_date",
        ),
    ]
