# Generated by Django 5.1.3 on 2025-01-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_remove_adminbooking_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="username",
        ),
    ]
