# Generated by Django 5.1.3 on 2025-01-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_remove_shorts_thumbnail_remove_video_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="refund_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
