# Generated by Django 5.1.3 on 2025-01-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_booking_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
