# Generated by Django 5.1.3 on 2025-01-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0015_alter_booking_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="refund_processed",
            field=models.BooleanField(default=False),
        ),
    ]
