# Generated by Django 5.1.3 on 2025-01-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0016_booking_refund_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="balance_payment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
