# Generated by Django 5.1.3 on 2025-01-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0017_booking_balance_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminbooking",
            name="caterer_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="entertainer_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="tailor_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
