# Generated by Django 5.1.3 on 2025-01-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_alter_adminbooking_caterer_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_payment_updated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="caterer_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="entertainer_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="tailor_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
