# Generated by Django 5.1.3 on 2025-01-21 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_booking_is_paid_booking_total_payment_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminbooking",
            name="username",
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="booking",
            field=models.ForeignKey(
                limit_choices_to={"status": "pending"},
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.booking",
            ),
        ),
    ]
