# Generated by Django 5.1.3 on 2025-01-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0020_remove_adminbooking_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminbooking",
            name="caterer_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("nil", "Nil"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="entertainer_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("nil", "Nil"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("nil", "Nil"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adminbooking",
            name="tailor_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("nil", "Nil"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
