# Generated by Django 5.1.3 on 2025-01-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0021_alter_adminbooking_caterer_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminbooking",
            name="booking",
            field=models.ForeignKey(
                limit_choices_to={"status": "confirmed"},
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.booking",
            ),
        ),
    ]
