# Generated by Django 5.1.3 on 2025-01-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0022_alter_adminbooking_booking"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Music",
        ),
    ]
