# Generated by Django 5.1.7 on 2025-03-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='adopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
