# Generated by Django 5.1.7 on 2025-03-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_adopt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adopt',
            new_name='adopt_table',
        ),
    ]
