# Generated by Django 5.1.7 on 2025-03-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_adopt_adopt_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.IntegerField()),
                ('pet', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=True)),
                ('message', models.CharField(max_length=60)),
            ],
        ),
    ]
