# Generated by Django 5.1.7 on 2025-04-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_appoinment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='message',
        ),
    ]
