# Generated by Django 5.1.7 on 2025-04-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_adopt_table_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='name',
            new_name='username',
        ),
    ]
