# Generated by Django 5.1.7 on 2025-04-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_name_appoinment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='fullname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
