# Generated by Django 5.1.7 on 2025-04-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_appoinment_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='appoinment',
            name='username',
        ),
    ]
