# Generated by Django 5.1.7 on 2025-04-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_fullname_appoinment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopt_table',
            old_name='name',
            new_name='username',
        ),
    ]
