# Generated by Django 5.1.7 on 2025-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_name_adopt_table_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt_table',
            name='fullname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
