# Generated by Django 5.1.7 on 2025-04-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_addproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
