# Generated by Django 5.1.7 on 2025-04-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
