# Generated by Django 5.2 on 2025-04-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_cart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
