# Generated by Django 5.2 on 2025-04-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_login_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
    ]
