# Generated by Django 5.2 on 2025-04-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_cart_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='addadopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('behaviour', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
