# Generated by Django 5.2 on 2025-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_addadopt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addadopt',
            name='behaviour',
            field=models.CharField(),
        ),
    ]
