# Generated by Django 5.1.6 on 2025-04-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_contact_alter_addadopt_behaviour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_table',
        ),
    ]
