# Generated by Django 5.1.6 on 2025-04-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_rename_contact_contact_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_table',
            old_name='fullname',
            new_name='name',
        ),
    ]
