# Generated by Django 5.1.7 on 2025-04-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='user',
            new_name='username',
        ),
    ]
