# Generated by Django 5.1.7 on 2025-04-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_rename_user_passwordreset_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.login'),
        ),
    ]
