# Generated by Django 5.1.7 on 2025-04-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_passwordreset_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='username',
            new_name='user',
        ),
    ]
