# Generated by Django 5.1.7 on 2025-05-07 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_myorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myorder',
        ),
    ]
