# Generated by Django 5.1.7 on 2025-05-07 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_alter_wishlist_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.addproduct'),
        ),
    ]
