# Generated by Django 5.1.7 on 2025-05-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_alter_wishlist_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='myorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_status', models.CharField(max_length=20)),
                ('payment_amount', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.addproduct')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
            ],
        ),
    ]
