# Generated by Django 5.0.6 on 2024-06-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Models',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='ProductName',
            field=models.CharField(max_length=30),
        ),
    ]
