# Generated by Django 5.0.4 on 2024-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Price',
            field=models.IntegerField(max_length=10),
        ),
    ]
