# Generated by Django 4.1.13 on 2024-06-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_alter_add_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.add_product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.register')),
            ],
        ),
    ]
