# Generated by Django 4.1.13 on 2024-07-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('delivery_date', models.DateField()),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('payment_status', models.CharField(max_length=20, null=True)),
                ('purchase_date', models.DateTimeField(auto_now=True, null=True)),
                ('product_status', models.CharField(default='Order Placed', max_length=50, null=True)),
                ('instruction', models.CharField(default='Your Order Has Been Successfully Placed', max_length=50, null=True)),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.add_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.register')),
            ],
        ),
    ]
