# Generated by Django 4.1.13 on 2024-07-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_details', models.CharField(max_length=20)),
                ('qunatity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('payment_status', models.CharField(default='NOT PAID', max_length=20)),
                ('delivery_status', models.CharField(default='pending', max_length=20)),
                ('dboy_name', models.CharField(default='abc', max_length=20)),
                ('address', models.CharField(default='NIL', max_length=200)),
                ('address_city', models.CharField(max_length=20)),
                ('address_district', models.CharField(max_length=20)),
                ('address_state', models.CharField(max_length=20)),
                ('address_pincode', models.IntegerField(default=0)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.register')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
