# Generated by Django 4.1.13 on 2024-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_order_details_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='dboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.IntegerField()),
                ('d_license', models.FileField(upload_to='')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('c_password', models.CharField(max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('work_status', models.CharField(default='free', max_length=20)),
            ],
        ),
    ]
