# Generated by Django 4.1.13 on 2024-07-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_dboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(default='NIL', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='address_city',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='address_district',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='address_pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='address_state',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
