# Generated by Django 4.1.13 on 2024-07-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_register_address_register_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
