# Generated by Django 6.0.2 on 2026-05-21 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='developerregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('bio', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('user_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='createproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.category')),
                ('technologies', models.ManyToManyField(to='webdevelopersite.technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='developerproposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_proposal', models.CharField(max_length=200)),
                ('project_budget', models.IntegerField(null=True)),
                ('progress', models.IntegerField(default=0)),
                ('project_status', models.CharField(default='pending', max_length=50, null=True)),
                ('advance_pay', models.IntegerField(null=True)),
                ('advance_status', models.CharField(default='pending', max_length=50)),
                ('final_payment_status', models.CharField(default='pending', max_length=50)),
                ('admin_commission', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.createproject')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.developerregister')),
            ],
        ),
        migrations.CreateModel(
            name='developerportfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_type', models.CharField(max_length=50, null=True)),
                ('project_technology', models.CharField(max_length=50, null=True)),
                ('project_duration', models.IntegerField(null=True)),
                ('project_demo', models.URLField(null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.developerregister')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.developerregister')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='AdminCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('admin_amount', models.IntegerField()),
                ('developer_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.createproject')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.developerregister')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.chatroom')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webdevelopersite.developerportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.createproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='userreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.developerregister')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.createproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='worksubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('upload_status', models.CharField(default='pending', max_length=50)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.developerregister')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdevelopersite.createproject')),
            ],
        ),
    ]
