# Generated by Django 6.0.1 on 2026-02-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('driver', 'Driver'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('mason', 'Mason'), ('cleaner', 'Cleaner'), ('security', 'Security Guard'), ('delivery', 'Delivery Boy'), ('helper', 'Helper / Labour'), ('catering', 'Catering Staff')], max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.user_register')),
            ],
        ),
    ]
