# Generated by Django 6.0.1 on 2026-02-10 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_profile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='worker_documents/'),
        ),
        migrations.AddField(
            model_name='worker_profile',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker_profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user_register')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.worker_profile')),
            ],
        ),
    ]
