# Generated by Django 6.0.1 on 2026-02-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_worker_profile_document_worker_profile_is_terminated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_profile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
