# Generated by Django 6.0.1 on 2026-02-18 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_worker_profile_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='requested_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
