# Generated by Django 6.0.1 on 2026-02-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_booking_fare_booking_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
