# Generated by Django 6.0.1 on 2026-02-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid_cash', 'Paid - Cash'), ('paid_online', 'Paid - Online')], default='unpaid', max_length=20),
        ),
    ]
