# Generated by Django 4.2.11 on 2024-03-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=40)),
                ('Time', models.CharField(max_length=10)),
                ('Ticket_price', models.CharField(max_length=10)),
                ('Available_tickets', models.IntegerField()),
                ('Event_image', models.FileField(upload_to='')),
                ('Status', models.CharField(default='pending', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Register_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.CharField(max_length=10)),
                ('Experience', models.IntegerField()),
                ('Password', models.CharField(max_length=12)),
                ('Status', models.CharField(default='pending', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Register_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.CharField(max_length=10)),
                ('issue', models.CharField(max_length=100)),
                ('eventname', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register_user')),
            ],
        ),
    ]
