# Generated by Django 4.2.11 on 2024-03-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='CPassword',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
