# Generated by Django 4.2.11 on 2024-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_register_manager_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
