# Generated by Django 4.2.11 on 2024-03-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_events_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='CPassword',
        ),
    ]
