# Generated by Django 4.2.11 on 2024-04-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_register_user_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_manager',
            name='CPassword',
        ),
        migrations.AlterField(
            model_name='register_user',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
