# Generated by Django 4.2.11 on 2024-04-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_register_manager_cpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Discription',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='picture',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
