# Generated by Django 4.2.11 on 2024-04-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_events_discription_events_picture_events_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='events',
            old_name='video',
            new_name='Video',
        ),
        migrations.RemoveField(
            model_name='events',
            name='picture',
        ),
        migrations.AddField(
            model_name='events',
            name='Sub_images',
            field=models.ManyToManyField(null=True, to='app.images'),
        ),
    ]
