# Generated by Django 4.2.11 on 2024-04-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_images_rename_video_events_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='Available_tickets',
            new_name='Bronze_Available_tickets',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='Ticket_price',
            new_name='Bronze_Ticket_price',
        ),
        migrations.AddField(
            model_name='events',
            name='Gold_Available_tickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='Gold_Ticket_price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='Silver_Available_tickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='Silver_Ticket_price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
