# Generated by Django 4.2.11 on 2024-04-24 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_available_tickets_events_bronze_available_tickets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_tickets', models.IntegerField(default=1)),
                ('total_amount', models.IntegerField(default=0)),
                ('ticket_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.events')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register_user')),
            ],
        ),
    ]
