# Generated by Django 4.2.11 on 2024-05-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goldamount', models.IntegerField(default=0)),
                ('silveramount', models.IntegerField(default=0)),
                ('bronzeamount', models.IntegerField(default=0)),
            ],
        ),
    ]
