# Generated by Django 4.2.11 on 2024-05-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('payment_status', models.CharField(max_length=20, null=True)),
                ('purchase_date', models.DateTimeField(auto_now=True, null=True)),
                ('product_status', models.CharField(default='paid', max_length=50, null=True)),
                ('instruction', models.CharField(default='Your Order Has Been Successfully\xa0Placed', max_length=50, null=True)),
                ('eventdetails_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.events')),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register_user')),
            ],
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='bronzeamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='goldamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='silveramount',
            field=models.IntegerField(default=0),
        ),
    ]
