# Generated by Django 4.2.11 on 2024-05-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_booking_bronzeamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='bookingdetails_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.booking'),
            preserve_default=False,
        ),
    ]
