# Generated by Django 4.2.11 on 2024-05-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_deliverydetails_bookingdetails_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetails',
            name='total_price',
        ),
    ]
