# Generated by Django 4.2.11 on 2024-05-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_deliverydetails_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='instruction',
            field=models.CharField(default='Your Order Has Been Successfully\xa0Placed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='product_status',
            field=models.CharField(default='paid', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='deliverydetails',
        ),
    ]
