# Generated by Django 4.2.11 on 2024-05-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_booking_instruction_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='purchase_date',
            new_name='booked_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='product_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_status',
            field=models.CharField(default='booked', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='paid', max_length=20, null=True),
        ),
    ]
