# Generated by Django 4.2.11 on 2024-05-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_purchase_date_booking_booked_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='PAID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_status',
            field=models.CharField(default='BOOKED', max_length=50, null=True),
        ),
    ]
