# Generated by Django 5.2 on 2025-04-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
