# Generated by Django 5.2 on 2025-04-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_wishlist_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='house',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='road_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
