# Generated by Django 5.2 on 2025-04-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_user_register_city_user_register_house_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='house',
            new_name='building_name',
        ),
    ]
