# Generated by Django 5.2 on 2025-05-02 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_boy',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='product_status',
            field=models.CharField(default='order placed', max_length=30),
        ),
    ]
