# Generated by Django 5.2 on 2025-05-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_orders_delivery_boy_orders_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_boy',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
