# Generated by Django 5.2 on 2025-05-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_orders_delivery_boy'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_boy_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('driving_license_no', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(default='Free', max_length=30)),
            ],
        ),
    ]
