# Generated by Django 5.2 on 2025-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_delivery_boy_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_boy_register',
            name='work_status',
            field=models.CharField(default='Free', max_length=30),
        ),
        migrations.AlterField(
            model_name='delivery_boy_register',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
