# Generated by Django 5.1.6 on 2025-05-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_delivery_boy_register_work_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_boy_register',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user_register')),
            ],
        ),
    ]
