# Generated by Django 5.1.2 on 2024-10-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_discription', models.TextField(max_length=255)),
                ('service_amount', models.FloatField()),
            ],
        ),
    ]
