# Generated by Django 5.1.2 on 2024-10-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0003_services_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
