# Generated by Django 5.1.2 on 2024-11-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0005_userbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='time_slot',
            field=models.CharField(max_length=15),
        ),
    ]
