# Generated by Django 5.0.2 on 2024-11-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0007_bookingorders_delete_services_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingorders',
            old_name='timslot',
            new_name='time_slot',
        ),
    ]
