# Generated by Django 5.0.2 on 2024-11-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0009_delete_userbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorders',
            name='payment_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
