# Generated by Django 5.0.2 on 2024-11-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0010_bookingorders_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorders',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
