# Generated by Django 5.0.2 on 2024-11-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0012_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorders',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
