# Generated by Django 5.1.3 on 2024-11-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0013_bookingorders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.FileField(upload_to='')),
                ('product_price', models.CharField(max_length=255)),
                ('product_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serv_Booking.user_details')),
            ],
        ),
    ]
