# Generated by Django 5.1.3 on 2024-11-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0014_userproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='status',
            field=models.CharField(default='pending', max_length=25),
        ),
    ]
