# Generated by Django 5.1.3 on 2024-11-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0015_userproducts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
