# Generated by Django 5.1.3 on 2024-11-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0016_userproducts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='purchase_status',
            field=models.CharField(default='not purchase', max_length=25),
        ),
    ]
