# Generated by Django 5.1.3 on 2024-11-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0018_alter_userproducts_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='product_price',
            field=models.CharField(max_length=255),
        ),
    ]
