# Generated by Django 5.1.3 on 2024-11-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0021_usercarts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproducts',
            name='purchase_status',
        ),
        migrations.AddField(
            model_name='userproducts',
            name='car_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='status',
            field=models.CharField(default='approved', max_length=25),
        ),
    ]
