# Generated by Django 5.1.3 on 2024-11-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0022_remove_userproducts_purchase_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.FileField(upload_to='')),
                ('product_price', models.CharField(max_length=255)),
                ('product_details', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default='approved', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usercarts',
            name='product_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serv_Booking.products'),
        ),
        migrations.AlterField(
            model_name='userwishlist',
            name='product_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serv_Booking.products'),
        ),
        migrations.DeleteModel(
            name='UserProducts',
        ),
    ]
