# Generated by Django 5.1.3 on 2024-11-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0023_products_alter_usercarts_product_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='pincode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
