# Generated by Django 5.1.3 on 2024-11-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0025_productsorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsorders',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
