# Generated by Django 5.1.3 on 2024-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0027_user_details_user_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vehicle Number')),
                ('license_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Driving License Number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=10, verbose_name='Current Status')),
                ('availability', models.BooleanField(default=True, verbose_name='Is Available?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='delivery_boy_profiles/', verbose_name='Profile Picture')),
            ],
            options={
                'verbose_name': 'Delivery Boy',
                'verbose_name_plural': 'Delivery Boys',
                'ordering': ['name'],
            },
        ),
    ]
