# Generated by Django 5.1.3 on 2024-12-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0028_deliveryboy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryboy',
            options={},
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='license_image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='availability',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='license_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='profile_picture',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
