# Generated by Django 5.1.3 on 2024-12-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0029_alter_deliveryboy_options_deliveryboy_license_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='availability',
        ),
    ]
