# Generated by Django 5.1.3 on 2024-12-02 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0030_remove_deliveryboy_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serv_Booking.deliveryboy')),
            ],
        ),
    ]
