# Generated by Django 5.1.3 on 2024-12-03 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0036_productsorders_delivery_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsorders',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Serv_Booking.deliveryboy'),
        ),
    ]
