# Generated by Django 5.1.3 on 2024-12-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0038_deliveryboy_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsorders',
            name='product_code',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
