# Generated by Django 5.1.3 on 2024-12-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0039_productsorders_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
