# Generated by Django 5.1.3 on 2024-12-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0042_services_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_discription',
            field=models.TextField(),
        ),
    ]
