# Generated by Django 5.1.3 on 2024-12-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0043_alter_services_service_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
