# Generated by Django 5.1.3 on 2024-12-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0044_user_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='license_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
