# Generated by Django 5.1.3 on 2024-12-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0045_deliveryboy_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorders',
            name='refund_status',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
