# Generated by Django 5.1.3 on 2024-12-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0046_bookingorders_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorders',
            name='refund_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
