# Generated by Django 5.1.3 on 2024-12-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0048_alter_bookingorders_refund_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingorders',
            name='refund_status',
        ),
    ]
