# Generated by Django 5.1.3 on 2024-12-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0049_remove_bookingorders_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorders',
            name='refund_status',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
