# Generated by Django 5.1.3 on 2024-12-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0051_productsorders_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsorders',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
