# Generated by Django 5.1.3 on 2024-12-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0054_productrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrate',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
