# Generated by Django 5.1.3 on 2025-01-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0055_productrate_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='address',
            new_name='area',
        ),
        migrations.AddField(
            model_name='user_details',
            name='housename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='landmark',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsorders',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
