# Generated by Django 5.1.3 on 2025-01-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serv_Booking', '0056_rename_address_user_details_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='work_status',
            field=models.CharField(default='free', max_length=255),
        ),
    ]
